version: 2
jobs:
  build:
    working_directory: ~/KleanActivityForResult
    docker:
      - image: circleci/android:api-26-alpha
    environment:
      TZ: Europe/Madrid
      JVM_OPTS: -Xmx3200m
      GRADLE_OPTS: '-Dorg.gradle.daemon=false'
      _JAVA_OPTIONS: "-Xms256m -Xmx1280m -XX:MaxPermSize=350m"
    steps:
      - checkout
      - restore_cache:
          key: jars--{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Download dependencies
          command: ./gradlew dependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars--{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Configure Gradle Properties
          command: echo "org.gradle.daemon=false" > ~/.gradle/gradle.properties && echo "org.gradle.jvmargs=-Xmx1536m -XX:MaxPermSize=512m -XX:+HeapDumpOnOutOfMemoryError" >> ~/.gradle/gradle.properties
      - run:
          name: Compile KleanActivityForResult
          command: ./gradlew clean build --stacktrace
      - store_artifacts:
          path: app/build/outputs
          destination: outputs
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results:
          path: app/build/test-results